@startuml

'https://plantuml.com/sequence-diagram
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members




package entite
{

    abstract class Entite <<abstract>>
    {
        + <<create>> Entite()
        + {abstract}attaquer(other: Entite)
        + {abstract}toString(): String
        + {abstract}getRepresentation(): String
        + seDeplacer()
        + getPv(): Integer
        + getDexterite(): Integer
        + getVitesse(): Integer
        + getInit(): Integer
        + getForce() : Integer
    }


    package personnage
    {
        class Personnage extends entite.Entite
        {
            - m_nom: String
            + <<create>> Personnage (Nom: String, race: Race, classe: Classe, inventory: Inventaire, stats: CaracteristiquesBase, equipPorte: EquipementPorte)
            + equiper (objet: Item)
            + ramasser (objet: Item)
            + getNom(): String
            + toString(): String
            + getRepresentation(): String
        }

        class EquipementPorte
        {
            + <<create>> EquipementPorte (arme: Arme, armure: Armure)
            + getArme(): Arme
            + getArmure(): Armure
            + toString(): String
        }

        class Inventaire
        {
            +toString(): String
        }

        package race
        {
            abstract class Race <<abstract>>
            {
                + toString(): String
                + <<create>> Race(stats: Caracteristiques)
            }

            class Humain implements Race
            {
                + toString(): String
                +<<create>> Humain(stats: Caracteristiques)
                +<<create>> Humain()
            }

            class Nain implements Race
            {
                + toString(): String
                + <<create>> Nain(stats: Caracteristiques)
                + <<create>> Nain()
            }

            class Elfe implements Race
            {
                + toString(): String
                + <<create>> Elfe(stats: Caracteristiques)
                + <<create>> Elfe()
            }

            class Halfelin implements Race
            {
                + toString(): String
                + <<create>> Halfelin(stats: Caracteristiques)
                + <<create>> Halfelin()
            }
        }

        package classe
        {
            abstract class Classe <<abstract>>
            {
                + toString(): String
                + <<create>> Classe(pv: Pv, equipement: Inventaire)
                + getPv(): Pv
            }

            class Guerrier implements Classe
            {
                + <<create>> Guerrier()
                + toString(): String
            }

            class Clerc implements Classe
            {
                + <<create>> Clerc()
                + toString(): String
            }

            class Magicien implements Classe
            {
                + <<create>> Magicien()
                + toString(): String
            }

            class Roublard implements Classe
            {
                + <<create>> Roublard()
                + toString(): String
            }
        }
    }

    package monstre
    {
        class Monstre extends entite.Entite
        {
            - m_numero : Optional<Integer>
            - m_classeArmure : Integer
            + <<create>> Monstre (portee : Integer, degats : Integer, espece : Espece)
            + <<create>> Monstre (portee : Integer, degats : Integer, espece : Espece, numero : Integer)
            + getClasseArmure() : Integer
            + getRepresentation(): String
            + toString(): String
        }

        class AttaqueMonstre
        {
            - m_portee : Integer
            - m_degats : Integer
            + getPorte(): Integer
            + getDegats(): Integer
        }

        class Espece
        {
            + m_nomEspece: String
            + <<create>> Espece (nomEspece : String)
            + getNomEspece(): String
            + toString()
        }
    }
}

package stats
{

    interface Caracteristique <<interface>>
    {
        + toString(): String
    }

    class CaracteristiquesBase implements Caracteristique
    {
        + <<create>> Caractéristiques (pv : Pv, force : Force, dexterite : Dexterite, vitesse : Vitesse, initiative : Initiative)
        + toString(): String
        + getPv(): Integer
        + getDexterite(): Integer
        + getVitesse(): Integer
        + getInit(): Integer
        + getForce() : Integer
    }

    class CaracteristiqueArme implements Caracteristique
    {
        + <<create>> CaracteristiqueArme()
        - m_degats : Integer
        - m_portee : Integer
        + getDegats(): Integer
        + getPortee(): Integer
        + toString(): String
    }

    class CaracteristiqueArmeDeGuerre implements Caracteristique
    {
        + getVitesse(): Vitesse
        + getForce(): Force
        + toString(): String
        + <<create>> CaracteristiqueArmeDeGuerre()
    }

    class CaracteristiqueArmureLourde implements Caracteristique
    {
        + getVitesse(): Vitesse
        + toString(): String
        + <<create>> CaracteristiqueArmureLourde()
    }

    class ClasseArmure implements Caracteristique
    {
        - m_classeArmure : Integer
        + toString(): String
        + getClasseArmure(): Integer
        + <<create>> ClasseArmure()
    }

    class Pv implements Caracteristique
    {
        - m_pvMax : Integer
        - m_currentPv : Integer
        + toString(): String
        + getPv(): Integer
        + <<create>> Pv()
    }

    class Force implements Caracteristique
    {
        - m_force : Integer
        + toString(): String
        + getForce(): Integer
        + <<create>> Force()
    }

    class Dexterite implements Caracteristique
    {
        - m_dexterite : Integer
        + toString(): String
        + getDexterite: Integer
        + <<create>> Dexterite()
    }

    class Vitesse implements Caracteristique
    {
        - m_vitesse : Integer
        + toString(): String
        + getVitesse(): Integer
        + <<create>> Vitesse()
    }

    class Initiative implements Caracteristique
    {
        - m_initiative : Integer
        + toString(): String
        + getInitiative(): Integer
        + <<create>> Initiative ()
    }


}

package objet
{
    abstract class Item <<abstract>>
    {
        + <<create>> Item ()
        + {abstract}toString(): String
    }


    abstract class Arme <<abstract>> implements Item
    {

        + <<create>> Arme (carac: CaracteristiqueArme)
        + getDegats(): Integer
        + getPortee(): Integer
        + toString(): String
    }

     abstract class Armure <<abstract>> implements Item
     {
        + <<create>> Armure (carac: ClasseArmure)
        + getClasseArmure(): Integer
        + toString(): String
     }

     abstract class ArmureLourde <<abstract>> extends Armure
     {
        + <<create>> ArmureLourde(carac: ClasseArmure)
        + toString(): String
     }

     abstract class ArmureLegere <<abstract>>  extends Armure
     {
        + <<create>> ArmureLegere (carac: ClasseArmure)
        + toString(): String
     }

     abstract class ArmeCourante <<abstract>> extends Arme
     {
        + <<create>> ArmeCourante  (carac: CaracteristiqueArme)
        + toString(): String
     }

     abstract class ArmeDeGuerre <<abstract>> extends Arme
     {
        + <<create>> ArmeDeGuerre  (carac: CaracteristiqueArme)
        + toString(): String
     }

     abstract class  ArmeDistance <<abstract>> extends Arme
     {
        + <<create>> ArmeDistance (carac: CaracteristiqueArme)
        + toString(): String
     }

     class ArmureEcailles extends ArmureLegere
     {
        + <<create>> ArmureEcaille()
        + toString(): String
     }

     class DemiPlate extends ArmureLegere
     {
        + <<create>> ArmureLourde()
        + toString(): String
     }

     class CoteMailles extends ArmureLourde
     {
        + <<create>> CoteMailles()
        + toString(): String
     }

     class Harnois extends ArmureLourde
     {
        + <<create>> Harnois()
        + toString(): String
     }

     class Baton extends ArmeCourante
     {
        + <<create>> Baton()
        + toString(): String
     }

     class MasseDarme extends ArmeCourante
     {
        + <<create>> MasseDarme()
        + toString(): String
     }

     class EpeeLongue extends ArmeDeGuerre
     {
        + <<create>> EpeeLongue()
        + toString(): String
     }

     class Rapiere extends ArmeDeGuerre
     {
        + <<create>> Rapiere()
        + toString(): String
     }

     class ArbaleteLegere extends ArmeDistance
     {
        + <<create>> ArbaleteLegere()
        + toString(): String
     }

     class Fronde extends ArmeDistance
     {
        + <<create>> Fronde()
        + toString(): String
     }

     class ArcCourt extends ArmeDistance
     {
        + <<create>> ArcCourt()
        + toString(): String
     }
}

 class De
 {
    - m_nbDes : Integer
    - m_nbFace : Integer
    + jeterDes (nbDes : Integer, nbFaceDes : Integer) : Integer
    + toString()
 }

 package donjon
 {

    class Donjon
    {
        - m_longueur : Integer
        - m_largeur : Integer
    }

    class Case
    {
        - m_x : Integer
        - m_y : Integer

    }

    class PositionObstacle
    {
       - dictionnaire : Map <Case, Obstacle>
       + toString(): String
    }

    class PositionEquipement
    {
       - dictionnaire : Map <Case, Item>
       + toString(): String
    }

    class PositionEntite
    {
        - dictionnaire : Map <Case, Entite>
       + toString(): String
    }

    class Obstacle
    {
       + toString(): String
    }
 }

Donjon "1..*" *--> " 1..* \nm_listeItems" PositionEquipement : detient
Donjon "1..*" *--> " 1..* \nm_listeEntite" PositionEntite : detient
Donjon "1..*" *--> " 1..* \nm_listeObstacle" PositionObstacle : detient

PositionObstacle "1..*" *--> " 1..* \n" Obstacle : detient
PositionEquipement "1..*" *--> " 1..* \n" Item : detient
PositionEntite "1..*" *--> " 1..* \n" Entite : detient

CaracteristiquesBase "1" o--> " 1 \nm_pv" Pv : possède
CaracteristiquesBase "1" o--> " 1 \nm_force" Force : possède
CaracteristiquesBase "1" o--> " 1 \nm_vitesse" Vitesse : possède
CaracteristiquesBase "1" o--> " 1 \nm_dexterite" Dexterite : possède
CaracteristiquesBase "1" o--> " 1 \nm_initiative" Initiative : possède

Entite "1" *--> " 1 \nm_caracteristiques" Caracteristique : detient

Personnage "1" *--> " 1 \nm_inventaire" Inventaire : possède
Personnage "1" o--> " 1 \nm_race" Race : est
Personnage "1" o--> " 1 \nm_classe" Classe : possède
Personnage "1" *--> " 1..* \nm_equipement" EquipementPorte : possède

Inventaire "1..*" o--> " 1..* \nm_listeitems" objet.Item : possède

Monstre "1" o--> " 1 \nm_espece" Espece : est
Monstre "1" *--> " 1 \nm_attaque" AttaqueMonstre : possède

Race "1" *--> " 1 \nm_caractéristiques" stats.Caracteristique : detient

Classe "1..*" *--> " 1..* \nm_equipement" Inventaire : detient
Classe "1" o--> " 1 \nm_pv" Caracteristique : detient

EquipementPorte "1" *--> " 1 \nm_arme" Arme : contient
EquipementPorte "1" *--> " 1 \nm_armure" Armure : contient

Item "1" *--> " 1 \nm_caractéristiques" Caracteristique : possède

CaracteristiqueArmureLourde "1" *--> " 1 \nm_vitesse" Vitesse : possède

CaracteristiqueArmeDeGuerre"1" *--> " 1 \nm_vitesse" Vitesse : possède
CaracteristiqueArmeDeGuerre "1" *--> " 1 \nm_force" Force : possède


@enduml

