@startuml

'https://plantuml.com/sequence-diagram
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members




package entite
{

    abstract class Entite <<abstract>>
    {
        + <<create>> Entite(nom: String)
        + attaquer(other: Entite)
        + {abstract}toString(): String
        + seDeplacer()
        + getPv(): Integer
        + getDexterite(): Integer
        + getVitesse(): Integer
        + getInit(): Integer
        + getForce() : Integer
    }


    package personnage
    {
        class Personnage extends entite.Entite
        {
            - m_nom: String
            + <<create>> Personnage (Nom: String, race: Race, classe: Classe, inventory: Inventaire, stats: CaracteristiquesBase, equipPorte: EquipementPorte)
            + equiper (objet: Item)
            + ramasser (objet: Item)
            + getNom(): String
        }

        class EquipementPorte
        {
            + <<create>> EquipementPorte (arme: Arme, armure: Armure)
            + getArme(): Arme
            + getArmure(): Armure
            + toString(): String
        }

        class Inventaire
        {
            +toString(): String
        }

        package race
        {
            abstract class Race <<abstract>>
            {
                + toString(): String
                + <<create>> Race(stats: Caracteristiques)
            }

            class Humain implements Race
            {
                + toString(): String
                +<<create>> Humain(stats: Caracteristiques)
                +<<create>> Humain()
            }

            class Nain implements Race
            {
                + toString(): String
                + <<create>> Nain(stats: Caracteristiques)
                + <<create>> Nain()
            }

            class Elfe implements Race
            {
                + toString(): String
                + <<create>> Elfe(stats: Caracteristiques)
                + <<create>> Elfe()
            }

            class Halfelin implements Race
            {
                + toString(): String
                + <<create>> Halfelin(stats: Caracteristiques)
                + <<create>> Halfelin()
            }
        }

        package classe
        {
            abstract class Classe <<abstract>>
            {
                + toString(): String
                + <<create>> Classe(pv: Integer, equipement: Items[*])
                + getPv(): Integer
            }

            class Guerrier implements Classe
            {
                + <<create>> Guerrier()
                + toString(): String
            }

            class Clerc implements Classe
            {
                + <<create>> Clerc()
                + toString(): String
            }

            class Magicien implements Classe
            {
                + <<create>> Magicien()
                + toString(): String
            }

            class Roublard implements Classe
            {
                + <<create>> Roublard()
                + toString(): String
            }
        }
    }

    package monstre
    {
        class Monstre extends entite.Entite
        {
            - m_numero : Optional<Integer>
            - m_classeArmure : Integer
            + <<create>> Monstre (portee : Integer, degats : Integer, espece : Espece)
            + <<create>> Monstre (portee : Integer, degats : Integer, espece : Espece, numero : Integer)
            + getClasseArmure() : Integer
        }

        class AttaqueMonstre
        {
            - m_portee : Integer
            - m_degats : Integer
            + getPorte(): Integer
            + getDegats(): Integer
        }

        class Espece
        {
            + m_nomEspece: String
            + <<create>> Espece (nomEspece : String)
            + getNomEspece(): String
            + toString()
        }
    }
}

package stats
{
    class CaracteristiquesBase
    {
        + <<create>> Caractéristiques (pv : Integer, force : Integer, dextérité : Integer, vitesse : Integer, initiative : Integer)
        + toString(): String
        + getPv(): Integer
        + getDexterite(): Integer
        + getVitesse(): Integer
        + getInit(): Integer
        + getForce() : Integer
    }

    class ClasseArmure
    {
        - m_classeArmure : Integer
        + toString(): String
        + getClasseArmure(): Integer
    }

    class Pv
    {
        - m_pv : Integer
        + toString(): String
        + getPv(): Integer
    }

    class Force
    {
        - m_force : Integer
        + toString(): String
        + getForce(): Integer
    }

    class Dexterite
    {
        - m_dexterite : Integer
        + toString(): String
        + getDexterite: Integer
    }

    class Vitesse
    {
        - m_vitesse : Integer
        + toString(): String
        + getVitesse(): Integer
    }

    class Initiative
    {
        - m_initiative : Integer
        + toString(): String
        + getInitiative(): Integer
    }
}

package objet
{
    abstract class Item <<abstract>>
    {
        -m_nom : String
        + <<create>> Item (nom : String, stats: CaracteristiquesBase)
        + getNom(): String
    }


    abstract class Arme <<abstract>> implements Item
    {
        - m_degats : Integer
        - m_portee : Integer
        + <<create>> Arme (degats : Integer, portee : Integer, nom: String, stats: CaracteristiquesBase)
        + getDegats(): Integer
        + getPortee(): Integer
    }

     abstract class Armure <<abstract>> implements Item
     {
        + <<create>> Armure (armure : Integer, nom: String, stats: CaracteristiquesBase)
        + getClasseArmure(): Integer
     }

     class ArmureLourde  extends Armure
     {
        + <<create>> ArmureLourde(armure : Integer, nom: String, stats: CaracteristiquesBase)
     }

     class ArmureLegere  extends Armure
     {
        + <<create>> ArmureLegere (armure : Integer, nom: String, stats: CaracteristiquesBase
     }

     class ArmeCourante  extends Arme
     {
        + <<create>> ArmeCourante  (degats : Integer, portee : Integer, nom: String, stats: CaracteristiquesBase)
     }

     class ArmeDeGuerre  extends Arme
     {
        + <<create>> ArmeDeGuerre  (degats : Integer, portee : Integer, nom: String, stats: CaracteristiquesBase)
     }

     class ArmeDistance extends Arme
     {
        + <<create>> ArmeDistance (degats : Integer, portee : Integer, nom: String, stats: CaracteristiquesBase)
     }
}

 class De
 {
    - m_nbDes : Integer
    - m_nbFace : Integer
    + jeterDes (nbDes : Integer, nbFaceDes : Integer) : Integer
    + toString()
 }

 package donjon
 {

    class Donjon
    {
        - m_longueur : Integer
        - m_largeur : Integer
    }

    class Case
    {
        - m_x : Integer
        - m_y : Integer

    }

    class PositionObstacle
    {
       - dictionnaire : Map <Case, Obstacle>
       + toString(): String
    }

    class PositionEquipement
    {
       - dictionnaire : Map <Case, Item>
       + toString(): String
    }

    class PositionEntite
    {
        - dictionnaire : Map <Case, Entite>
       + toString(): String
    }

    class Obstacle
    {
       + toString(): String
    }
 }

Donjon "1..*" *--> " 1..* \nm_listeItems" PositionEquipement : detient
Donjon "1..*" *--> " 1..* \nm_listeEntite" PositionEntite : detient
Donjon "1..*" *--> " 1..* \nm_listeObstacle" PositionObstacle : detient

PositionObstacle "1..*" *--> " 1..* \n" Obstacle : detient
PositionEquipement "1..*" *--> " 1..* \n" Item : detient
PositionEntite "1..*" *--> " 1..* \n" Entite : detient

CaracteristiquesBase "1" o--> " 1 \nm_pv" Pv : possède
CaracteristiquesBase "1" o--> " 1 \nm_force" Force : possède
CaracteristiquesBase "1" o--> " 1 \nm_vitesse" Vitesse : possède
CaracteristiquesBase "1" o--> " 1 \nm_dexterite" Dexterite : possède
CaracteristiquesBase "1" o--> " 1 \nm_initiative" Initiative : possède

Entite "1" *--> " 1 \nm_caractéristiques" CaracteristiquesBase : detient

Personnage "1" *--> " 1 \nm_inventaire" Inventaire : possède
Personnage "1" o--> " 1 \nm_race" Race : est
Personnage "1" o--> " 1 \nm_classe" Classe : possède
Personnage "1" *--> " 1..* \nm_equipement" EquipementPorte : possède

Inventaire "1..*" o--> " 1..* \nm_listeitems" objet.Item : possède

Monstre "1" o--> " 1 \nm_espece" Espece : est
Monstre "1" *--> " 1 \nm_attaque" AttaqueMonstre : possède
Monstre "1" *--> " 1 \nm_classeArmure" stats.ClasseArmure : possède

Race "1" *--> " 1 \nm_caractéristiques" CaracteristiquesBase : detient

Classe "1..*" *--> " 1..* \nm_equipement" Inventaire : detient
Classe "1" o--> " 1 \nm_pv" Pv : detient

EquipementPorte "1" *--> " 1 \nm_arme" Arme : contient
EquipementPorte "1" *--> " 1 \nm_armure" Armure : contient

Armure "1" *--> " 1 \nm_armure" ClasseArmure : possède

ArmeDeGuerre "1" *--> " 1 \nm_vitesse" Vitesse : possède
ArmeDeGuerre "1" *--> " 1 \nm_force" Force : possède

ArmureLourde "1" *--> " 1 \nm_vitesse" Vitesse : possède

@enduml

