@startuml

'https://plantuml.com/sequence-diagram
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
skinparam linetype ortho
hide empty members

package jouable
{

    abstract class Jouable <<abstract>>
    {
        + <<create>> Jouable()
        + {abstract} attaquer(other: Jouable)
        + {abstract} toString(): String
        + {abstract} getRepresentation(): String
        + getCurrentPv(): Integer
        + getPvMax(): Integer
        + getDexterite(): Integer
        + getVitesse(): Integer
        + getInit(): Integer
        + getForce(): Integer
    }

    package personnage
    {
        class Personnage extends jouable.Jouable
        {
            - m_nom: String
            - m_listeSorts: Sorts[*]
            + <<create>> Personnage (nom: String, race: Race, classe: Classe, stats: CaracteristiquesBase)
            + equiperArme(Armure: armure)
            + equiperArmure(Arme: arme)
            + ramasser()
            + getNom(): String
            + toString(): String
            + getRepresentation(): String
        }
        interface AffichagePersonnageInterface <<interface>>
        {
            + choisirClasse() : String
            + choisirRace() : String
            + choisirNom() : String
            + afficherCaracteristiaque(CurrentPv: Integer, PvMax: Integer, Dexteriter: Integer, Force: Integer, Vitesse: Integer, Initiative: Integer) : String
        }


        Personnage "1" *--> "1 \nm_race" race.Race : est
        Personnage "1" *--> "1 \nm_classe" classe.Classe : possède

        package race
        {
            interface Race <<interface>>
            {
                + toString(): String
            }

            class Humain implements Race
            {
                + <<create>> Humain(stats: Caracteristiques)
                + <<create>> Humain()
                + getPv(): Integer
                + getCurrentPv(): Integer
                + getDexterite(): Integer
                + getVitesse(): Integer
                + getInit(): Integer
                + getForce(): Integer
                + toString(): String
            }

            class Nain implements Race
            {
                - m_force: Integer
                + <<create>> Nain(stats: Caracteristiques)
                + <<create>> Nain()
                + getForce(): Integer
                + toString(): String
            }

            class Elfe implements Race
            {
                - m_dexterite: Integer
                + <<create>> Elfe(stats: Caracteristiques)
                + <<create>> Elfe()
                + getDexterite(): Integer
                + toString(): String
            }

            class Halfelin implements Race
            {
                - m_dexterite: Integer
                - m_vitesse: Integer
                + <<create>> Halfelin(stats: Caracteristiques)
                + <<create>> Halfelin()
                + getDexterite(): Integer
                + getVitesse(): Integer
                + toString(): String
            }
        }

        package sorts
        {
            interface Sorts <<interface>>
            {
                + toString()
                + utiliser(lanceur: Personnage, Cibles: Jouable[*])
            }

            class Guerison implements Sorts
            {
                + toString()
                + utiliser(lanceur: Personnage, Object... cibles)
            }

            class BoogieWoogie implements Sorts
            {
                + toString()
                + utiliser(lanceur: Personnage, Object... cibles)
            }

            class ArmeMagique implements Sorts
            {
                + toString()
                + utiliser(lanceur: Personnage, Object... cibles)
            }

        }


        package classe
        {
            abstract class Classe <<abstract>>
            {
                - m_pv: Integer
                + toString(): String
                + <<create>> Classe(pv: Integer)
                + getPv(): Integer
                + getSorts(): Sorts[*]
            }

            class Guerrier extends Classe
            {
                + <<create>> Guerrier()
                + toString(): String
            }

            class Clerc extends Classe
            {
                + <<create>> Clerc()
                + toString(): String
            }

            class Magicien extends Classe
            {
                + <<create>> Magicien()
                + toString(): String
            }

            class Roublard extends Classe
            {
                + <<create>> Roublard()
                + toString(): String
            }
        }
    }

    package monstre
    {
        class Monstre extends jouable.Jouable
        {
            - m_numero: Integer
            - m_portee: Integer
            - m_degats: Integer
            - m_classeArmure: Integer
            - m_race: String
            + <<create>> Monstre(portee: Integer, degats: Integer, espece: String)
            + <<create>> Monstre(portee: Integer, degats: Integer, espece: String, numero: Integer)
            + getClasseArmure(): Integer
            + getRepresentation(): String
            + toString(): String
        }
        interface AffichageMonstreInterface <<interface>>
        {
            + choisirEspece() : String
            + choisirRepresentation() : String
            + choisirDegatAttaque() : String
            + choisirPorterAttaquechoisirPorterAttaque() : String
            + afficherCaracteristiaque(CurrentPv: Integer, PvMax: Integer, Dexteriter: Integer, Force: Integer, Vitesse: Integer, Initiative: Integer, Integer ClassArmure) : String
        }

    }
}

package stats
{
    class CaracteristiquesBase
    {
        - m_currentPv: Integer
        - m_pvMax: Integer
        - m_force: Integer
        - m_dexterite: Integer
        - m_vitesse: Integer
        - m_initiative: Integer
        + <<create>> CaracteristiquesBase(pv: Integer, force: Integer, dexterite: Integer, vitesse: Integer, initiative: Integer)
        + toString(): String
        + getPv(): Integer
        + getDexterite(): Integer
        + getVitesse(): Integer
        + getInit(): Integer
        + getForce(): Integer
    }

    Jouable "1" *--> "1 \nm_caracteristiques" stats.CaracteristiquesBase : détient
    Humain "1" *--> "1 \nm_caracteristiques" stats.CaracteristiquesBase : détient
}
package affichage
{
    class affichagePersonnage implements AffichagePersonnage
    {
        + choisirClasse() :String
        + choisirRace() :String
        + choisirNom() :String
        + afficherCaracteristiaque(CurrentPv: Integer, PvMax: Integer, Dexteriter: Integer, Force: Integer, Vitesse: Integer, Initiative: Integer) :String
    }
    class AffichageMonstre implements AffichageMonstreInterface
    {
        + choisirEspece() : String
        + choisirRepresentation() : String
        + choisirDegatAttaque() : String
        + choisirPorterAttaquechoisirPorterAttaque() : String
        + afficherCaracteristiaque(CurrentPv: Integer, PvMax: Integer, Dexteriter: Integer, Force: Integer, Vitesse: Integer, Initiative: Integer, Integer ClassArmure) : String
    }
}
package objet
{
    abstract class Equipement <<abstract>>
    {
        + getSymbole(): String
    }

    package armure
    {
        abstract class Armure <<abstract>> implements objet.Equipement
        {
            - m_classeArmure: Integer
            + <<create>> Armure(classeArmure: Integer)
            + getClasseArmure(): Integer
            + toString(): String
        }

        abstract class ArmureLourde <<abstract>> extends Armure
        {
            - m_vitesse: Integer
            + <<create>> ArmureLourde(classeArmure: Integer, vitesse: Integer)
            + toString(): String
            + getVitesse(): Integer
        }

        abstract class ArmureLegere <<abstract>> extends Armure
        {
            + <<create>> ArmureLegere()
            + toString(): String
        }

        class ArmureEcailles extends ArmureLegere
        {
            + <<create>> ArmureEcailles()
            + toString(): String
        }

        class DemiPlate extends ArmureLegere
        {
            + <<create>> DemiPlate()
            + toString(): String
        }

        class CoteMailles extends ArmureLourde
        {
            + <<create>> CoteMailles()
            + toString(): String
        }

        class Harnois extends ArmureLourde
        {
            + <<create>> Harnois()
            + toString(): String
        }
    }

    package arme
    {

        abstract class Arme <<abstract>> implements objet.Equipement
        {
            - m_degats: Integer
            - m_portee: Integer
            + <<create>> Arme(degats: Integer, portee: Integer)
            + getDegats(): Integer
            + getPortee(): Integer
            + setDegats(degats: Integer): Void
            + setPortee(portee: Integer): Void
            + toString(): String
        }

        abstract class ArmeCourante <<abstract>> extends Arme
        {
            + <<create>> ArmeCourante()
            + toString(): String
        }

        abstract class ArmeDeGuerre <<abstract>> extends Arme
        {
            - m_vitesse: Integer
            - m_force: Integer
            + <<create>> ArmeDeGuerre(vitesse: Integer, force: Integer)
            + toString(): String
            + getVitesse(): Integer
            + getForce(): Integer
        }

        abstract class ArmeDistance <<abstract>> extends Arme
        {
            + <<create>> ArmeDistance()
            + toString(): String
        }

        class Baton extends ArmeCourante
        {
            + <<create>> Baton()
            + toString(): String
        }

        class MasseDarme extends ArmeCourante
        {
            + <<create>> MasseDarme()
            + toString(): String
        }

        class EpeeLongue extends ArmeDeGuerre
        {
            + <<create>> EpeeLongue()
            + toString(): String
        }

        class Rapiere extends ArmeDeGuerre
        {
            + <<create>> Rapiere()
            + toString(): String
        }

        class EpeeDeuxMains extends ArmeDeGuerre
        {
            + <<create>> EpeeDeuxMains()
            + toString(): String
        }

        class ArbaleteLegere extends ArmeDistance
        {
            + <<create>> ArbaleteLegere()
            + toString(): String
        }

        class Fronde extends ArmeDistance
        {
            + <<create>> Fronde()
            + toString(): String
        }

        class ArcCourt extends ArmeDistance
        {
            + <<create>> ArcCourt()
            + toString(): String
        }
    }
}

Personnage "1..*" *--> "1..* \nm_inventaire" objet.Equipement : possède
Personnage "1" *--> "0..1 \nm_arme" objet.arme.Arme : possède
Personnage "1" *--> "1 \nm_armure" objet.armure.Armure : possède

Classe "1..*" *--> "1..* \nm_listeEquipement" objet.Equipement : détient

package donjon
{

    class Donjon
    {
        - m_longueur: Integer
        - m_largeur: Integer
        + <<create>> Donjon(longueur: Integer, largeur: Integer)
        + verifCasePrise(Position): Boolean
        + getLargeur(): Integer
        + getLongueur(): Integer
        + afficher(): String
        + toString(): String
    }

    class Position
    {
        - m_x: Integer
        - m_y: Integer
        + <<create>> Position(x: Integer, y: Integer)
        + toString(): String
    }

    class PositionsDesObstacles
    {
       + <<create>> PositionsDesObstacles()
       + ajouterObstacle()
       + toString(): String
       + {static} deplacerObstacle(Position)
    }

    class PositionsDesEquipements
    {
       + <<create>> PositionsDesEquipements()
       + ajouterEquipement(Position, Equipement)
       + toString(): String
       + {static} deplacerEquipement(Position)
    }

    class PositionsDesJouables
    {
        + <<create>> PositionsDesJouables()
        + ajouterJouable(Position, Jouable)
        + toString(): String
        + {static} deplacerJouable(Position)
    }

}
Donjon "1" *--> "1 \nm_dicoItems" PositionsDesEquipements : détient
Donjon "1" *--> "1 \nm_dicoJouable" PositionsDesJouables : détient
Donjon "1" *--> "1 \nm_dicoObstacle" PositionsDesObstacles : détient

PositionsDesEquipements "1..*" o--> "1..* \nm_positionEquipement" Equipement : détient
PositionsDesJouables "1..*" o--> "1..* \nm_positionJouable" Jouable : détient
PositionsDesObstacles "1..*" o--> "1..* \nm_positionObstacle" Position : détient


package partie {

    class MaitreDuJeu {
        + lancerPartie(): void
        + afficherEtat(): void
    }

    class GestionTour {
        - m_tourActuel: Integer
        + initialiserOrdre()
        + prochainTour(): Jouable
        + changerOrdre(Jouable)
    }

    class InitialiseurPartie {
        + creerPersonnages(): Personnage[*]
        + creerDonjon(): Donjon
        + creerMonstres(): Monstre[*]
    }

    class ExplorationDonjon {
        + jouerTour(Jouable)
        + deplacer(Jouable)
        + attaquer(Jouable)
        + ramasser(Jouable)
    }

    class De {
        - m_nbDes: Integer
        - m_nbFaces: Integer
        + jeter(): Integer
        + toString(): String
    }

    MaitreDuJeu "1" o--> "1 \nm_initPartie" InitialiseurPartie : utilise
    MaitreDuJeu "1" o--> "1 \nm_gestionTour" GestionTour : utilise
    MaitreDuJeu "1" o--> "1 \nm_dungeonExplorer" ExplorationDonjon : utilise

    GestionTour "1..*" o--> "1..* \nm_ordreJouable" Jouable : gère
    ExplorationDonjon "1..*" o--> "1..* " Jouable : m_listeJouable
}

class main
{
    + {static} main(args: String[])
}

objet.arme.Arme "1" *--> "1 \nm_deDegats" partie.De : utilise
InitialiseurPartie .> Donjon : <<instantiate>>

Classe "0..*" o--> "0..* \nm_listeSorts" jouable.personnage.sorts.Sorts : a des

main .> MaitreDuJeu : <<instantiate>>
main .> Donjon : <<instantiate>>
main .> De : <<instantiate>>

MaitreDuJeu "1" o--> "1 \nm_donjon" Donjon : gère

@enduml


