@startuml

'https://plantuml.com/sequence-diagram
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
skinparam linetype ortho
hide empty members

package jouable
{
    abstract class Jouable <<abstract>>
    {
        # m_caracteristiques: CaracteristiquesBase
        + <<create>> Jouable()
        + {abstract} attaquer(other: Jouable): AttackResult
        + {abstract} ajouterJouable(position: Position, listeJouables: PositionJouables)
        + {abstract} setId(id: Integer)
        + {abstract} toString(): String
        + {abstract} getSymbole(): String
        + {abstract} getNom(): String
        + {abstract} setSymbole(symbole: String)
        + getCurrentPv(): Integer
        + getPvMax(): Integer
        + getDexterite(): Integer
        + getVitesse(): Integer
        + getInit(): Integer
        + getForce(): Integer
        + getClasseArmure(): Integer
        + setPv()
        + setDexterite()
        + setVitesse()
        + setInit(
        + setForce()
        + setClasseArmure()
    }

    jouable.Jouable .> donjon.Donjon

    enum ActionResult <<enumerate>>
    {
        SUCCESS
        OBSTACLE
        OUT_OF_REACH
        FAILURE
        NO_ITEM
        NO_WEAPON
        ITEM
        OCCUPIED_POSITION
        OUT_OF_BONDS
    }

    class AttackResult
    {
        - m_status: ActionResult
        - m_jetAttaque: Integer
        - m_degats: Integer
        + <<create>> AttackResult(status: ActionResult, jetAttaque: Integer, degats: Integer)
        + getStatus(): AttackResult
        + getJetAttaque(): Integer
        + getDeDegats(): Integer
    }

    AttackResult .> ActionResult : <<use>>

    package personnage
    {

        class Personnage extends jouable.Jouable
        {
            - m_nom: String
            + <<create>> Personnage (nom: String, race: Race, classe: Classe, stats: CaracteristiquesBase)
            + <<create>> Personnage ()
            + attaquer(other: Position, Donjon donjon): AttackResult
            + equiper(item: Equipement)
            + ramasser(pos: Position, Donjon donjon)
            + ajouterJouable(position: Position, listeJouables: PositionJouables)
            + setId(id: Integer)
            + getNom(): String
            + getSymbole(): String
            + setSymbole(symbole: String)
            + setArmure(armure: Armure)
            + setArme(arme: Arme)
            + getArmure(): Armure
            + getArme(): Arme
            + getClasse(): Classe
            + getInventaire(): Inventaire
            + getStringArmure(): String
            + getStringArme(): String
            + toString(): String
            + getRepresentation(): String
            + equals(other: Object): boolean
        }

        class Inventaire
        {
            + <<create>> Inventaire ()
            + <<create>> Inventaire (listequipement: Equipement[*])
            + ajouterEquipement(item: Equipement)
            + retirerEquipement(item: Equipement)
            + getEquipement(item: Equipement): Equipement
            + getEquipement(index: Integer): Equipement
            + setInventaire(listequipement: Equipement[*])
            + getNbEquipement(): Integer
            + toString(): String
        }

        Personnage "1" *--> "1..* \nm_inventaire" Inventaire: a >
        Inventaire "1" *--> "1..* \nm_inventaire" objet.Equipement: a >

        interface AffichagePersonnageInterface <<interface>>
        {
            + choisirClasse() : String
            + choisirRace() : String
            + choisirNom() : String
            + afficherCaracteristiaque(CurrentPv: Integer, PvMax: Integer, Dexteriter: Integer, Force: Integer, Vitesse: Integer, Initiative: Integer) : String
        }


        Personnage "1" *--> "1 \nm_race" race.Race : est
        Personnage "1" *--> "1 \nm_classe" classe.Classe : possède

        package race
        {
            interface Race <<interface>>
            {
                + toString(): String
                + ajouterInitRacePerso(perso: Personnage)
            }

            class Humain implements Race
            {
                + <<create>> Humain()
                + ajouterInitRacePerso(perso: Personnage)
                + toString(): String
            }

            class Nain implements Race
            {
                - m_force: Integer
                + <<create>> Nain()
                + getForce(): Integer
                + toString(): String
                + ajouterInitRacePerso(perso: Personnage)
            }

            class Elfe implements Race
            {
                - m_dexterite: Integer
                + <<create>> Elfe()
                + ajouterInitRacePerso(perso: Personnage)
                + getDexterite(): Integer
                + toString(): String
            }

            class Halfelin implements Race
            {
                - m_dexterite: Integer
                - m_vitesse: Integer
                + <<create>> Halfelin()
                + getDexterite(): Integer
                + getVitesse(): Integer
                + toString(): String
                + ajouterInitRacePerso(perso: Personnage)
            }
        }

        package sorts
        {
            interface Sorts <<interface>>
            {
                + toString()
            }

            class Guerison implements Sorts
            {
                + toString()
                + lancerSort(cible: Personnage, pvSoigne: Integer): ActionResult
            }

            class BoogieWoogie implements Sorts
            {
                + toString()
                + lancerSort(cible1: Personnage, cible2: Personnage, donjon: Donjon): ActionResult
            }

            class ArmeMagique implements Sorts
            {
                + toString()
                + lancerSort(cible: Personnage, arme_cible: Arme): ActionResult
            }

        }


        package classe
        {
            abstract class Classe <<abstract>>
            {
                # m_pv: Integer
                # m_sorts: Sorts[*]
                # m_equipement: Equipement[*]
                + <<create>> Classe(pv: Integer)
                + <<create>> Classe(pv: Integer, equipement: Equipement[*])
                + <<create>> Classe(pv: Integer, equipement: Equipement[*], sorts: Sorts[*])
                + toString(): String
                + getPvClasse(): Integer
                + {abstract} ajouterClasseInitPerso()
                + getPv(): Integer
                + getListeEquipement(): Equipement[*]
                + getSorts(): Sorts[*]
                + equals(other: Object): Boolean
            }

            class Guerrier extends Classe
            {
                + <<create>> Guerrier()
                + toString(): String
                + ajouterClasseInitPerso()
            }

            class Clerc extends Classe
            {
                + <<create>> Clerc()
                + toString(): String
                + ajouterClasseInitPerso()
            }

            class Magicien extends Classe
            {
                + <<create>> Magicien()
                + toString(): String
                + ajouterClasseInitPerso()
            }

            class Roublard extends Classe
            {
                + <<create>> Roublard()
                + toString(): String
                + ajouterClasseInitPerso()
            }
        }
    }

    package monstre
    {
        class Monstre extends jouable.Jouable
        {
            - m_id: Integer
            - m_portee: Integer
            - m_degats: De
            - m_espece: String
            - m_classeArmure: Integer
            - m_symbole: String
            - m_race: String
            + <<create>> Monstre(portee: Integer, degats: De, espece: String, symbole: String)
            + <<create>> Monstre()
            + CopierDepuis(autre: Monstre)
            + {static} creerDragon(): Monstre
            + {static} creerGobelin(): Monstre
            + {static} creercreerDemogorgon(): Monstre
            + attaquer(other: Position, donjon: (Donjon)
            + ajouterJouable(position: Position, listeJouables: PositionsDesJouables)
            + getClasseArmure(): Integer
            + getSymbole(): String
            + setSymbole(symbole: String)
            + getRepresentation(): String
            + toString(): String
            + getNomArmure: String
            + getStringArmure: String
            + getNom(): String
            + equals(other: Object): String
        }

        interface AffichageMonstreInterface <<interface>>
        {
            + choisirEspece() : String
            + choisirRepresentation() : String
            + choisirDegatAttaque() : String
            + choisirPorterAttaquechoisirPorterAttaque() : String
            + afficherCaracteristiaque(CurrentPv: Integer, PvMax: Integer, Dexteriter: Integer, Force: Integer, Vitesse: Integer, Initiative: Integer, Integer ClassArmure) : String
        }

    }
}

package stats
{
    class CaracteristiquesBase
    {
        - m_currentPv: Integer
        - m_pvMax: Integer
        - m_force: Integer
        - m_dexterite: Integer
        - m_vitesse: Integer
        - m_initiative: Integer
        - m_armure: Integer
        + <<create>> CaracteristiquesBase(pv: Integer, force: Integer, dexterite: Integer, vitesse: Integer, initiative: Integer , armure: Integer)
        + <<create>> CaracteristiquesBase(CA: CaracteristiquesBase)
        + <<create>> CaracteristiquesBase()
        + ajouterClasseBonus(Integer: pv)
        + getPvMax(): Integer
        + getCurrentPv(): Integer
        + getDexterite(): Integer
        + getVitesse(): Integer
        + getInit(): Integer
        + getForce(): Integer
        + getArmure(): Integer
        + toString(): String
        + setPv()
        + setDexterite()
        + setVitesse()
        + setInit(
        + setForce()
        + setArmure()
        + equals(other: CaracteristiquesBase): Boolean
        + toString(): String
    }

    Jouable "1" *--> "1 \nm_caracteristiques" stats.CaracteristiquesBase : détient
    Humain "1" *--> "1 \nm_caracteristiques" stats.CaracteristiquesBase : détient
}

package objet
{
    abstract class Equipement <<abstract>>
    {
        + getSymbole(): String
        + {abstract} equiper(perso: Personnage)
        + {abstract} ajouterBonus(bonus: Integer)
        + {abstract} getNomEquipement(): String
        + {abstract} equals(): Boolean
    }

    Equipement .> Personnage : <<use>>

    package armure
    {
        abstract class Armure <<abstract>> implements objet.Equipement
        {
            # m_classeArmure: Integer
            + <<create>> Armure(classeArmure: Integer)
            + <<create>> Armure()
            + equiper(perso: Personnage)
            + equiper(perso: Personnage)
            + getClasseArmure(): Integer
            + toString(): String
            + equals(other: Object): Boolean
        }

        abstract class ArmureLourde <<abstract>> extends Armure
        {
            - m_vitesse: Integer
            + <<create>> ArmureLourde(classeArmure: Integer)
            + <<create>> ArmureLourde()
            + equiper(perso: Personnage)
            + toString(): String
            + getVitesse(): Integer
            + equals(other: Object): Boolean
        }

        abstract class ArmureLegere <<abstract>> extends Armure
        {
            + <<create>> ArmureLegere()
            + <<create>> ArmureLegere(armure: Integer)
            + toString(): String
            + equals(other: Object): Boolean
        }

        class ArmureEcailles extends ArmureLegere
        {
            + <<create>> ArmureEcailles()
            + toString(): String
            + getNomEquipement(): String
            + equals(other: Object): Boolean
        }

        class DemiPlate extends ArmureLegere
        {
            + <<create>> DemiPlate()
            + getNomEquipement(): String
            + toString(): String
            + equals(other: Object): Boolean
        }

        class CoteMailles extends ArmureLourde
        {
            + <<create>> CoteMailles()
            + getNomEquipement(): String
            + toString(): String
            + equals(other: Object): Boolean
        }

        class Harnois extends ArmureLourde
        {
            + <<create>> Harnois()
            + getNomEquipement(): String
            + toString(): String
            + equals(other: Object): Boolean
        }
    }

    package arme
    {

        abstract class Arme <<abstract>> implements objet.Equipement
        {
            # m_degats: De
            # m_portee: Integer
            # m_bonusAttaque: Integer
            + <<create>> Arme(degats: Integer, portee: Integer)
            + <<create>> Arme()
            + ajouterBonus(bonus: Integer)
            + getDeDegats(): De
            + getPortee(): Integer
            + getBonusAttaque(): Integer
            + setDeDegats(degats: De)
            + setPortee(portee: Integer)
            + setBonusAttaque(bonus: Integer)
            + toString(): String
            + equals(other: Object): Boolean
        }


        package armedeguerre
        {

            abstract class ArmeDeGuerre <<abstract>> extends objet.arme.Arme
            {
                # m_vitesse: Integer
                # m_force: Integer
                + <<create>> ArmeDeGuerre(degats: De, portee: Integer, vitesse: Integer, force: Integer)
                + <<create>> ArmeDeGuerre()
                + equiper(perso: Personnage)
                + toString(): String
                + getVitesse(): Integer
                + setVitesse(vitesse: Integer)
                + getForce(): Integer
                + setForce(force: Integer)
                + equals(other: Object): Boolean
            }

            class EpeeLongue extends ArmeDeGuerre
            {
                + <<create>> EpeeLongue()
                + toString(): String
                + getNomEquipement(): String
                + equals(other: Object): Boolean
            }

            class Rapiere extends ArmeDeGuerre
            {
                + <<create>> Rapiere()
                + toString(): String
                + getNomEquipement(): String
                + equals(other: Object): Boolean
            }

            class EpeeDeuxMains extends ArmeDeGuerre
            {
                + <<create>> EpeeDeuxMains()
                + toString(): String
                + getNomEquipement(): String
                + equals(other: Object): Boolean
            }

        }

        package armedistance
        {

            abstract class ArmeDistance <<abstract>> extends objet.arme.Arme
            {
                + <<create>> ArmeDistance()
                + <<create>> ArmeDistance(degats: De, portee: Integer)
                + equiper(perso: Personnage)
                + toString(): String
            }

            class ArbaleteLegere extends ArmeDistance
            {
                + <<create>> ArbaleteLegere()
                + toString(): String
                + equals(other: Object): Boolean
                + getNomEquipement(): String
            }

            class Fronde extends ArmeDistance
            {
                + <<create>> Fronde()
                + toString(): String
                + getNomEquipement(): String
                + equals(other: Object): Boolean
            }

        }

        package armecourante
        {

            abstract class ArmeCourante <<abstract>> extends objet.arme.Arme
            {
                + <<create>> ArmeCourante()
                + <<create>> ArmeCourante(degats: De, portee: Integer)
                + toString(): String
                + equiper(perso: Personnage)
                + equals(other: Object): Boolean
            }

            class Baton extends ArmeCourante
            {
                + <<create>> Baton()
                + getNomEquipement(): String
                + toString(): String
                + equals(other: Object): Boolean
            }

            class MasseDarme extends ArmeCourante
            {
                + <<create>> MasseDarme()
                 + getNomEquipement(): String
                + toString(): String
                + equals(other: Object): Boolean
            }

            class ArcCourt extends ArmeDistance
            {
                + <<create>> ArcCourt()
                + equals(other: Object): Boolean
                + toString(): String
                + getNomEquipement(): String
            }

        }









    }
}

Personnage "1..*" *--> "1..* \nm_inventaire" objet.Equipement : possède
Personnage "1" *--> "0..1 \nm_arme" objet.arme.Arme : possède
Personnage "1" *--> "1 \nm_armure" objet.armure.Armure : possède

Classe "1..*" *--> "1..* \nm_listeEquipement" objet.Equipement : détient

package donjon
{
    class Donjon
    {
        - m_longueur: int
        - m_largeur: int
        - m_nom: String
        + <<create>> Donjon(listePersonnages: List<Personnage>)
        + <<create>> Donjon(longueur: int, largeur: int)
        + <<create>> Donjon(longueur: int, largeur: int,jouable: PositionsJouables, equipement: PositionsEquipement,obstacle: PositionsObstacle)
        + getNom(): String
        + getLargeur(): int
        + getLongueur(): int
        + getPositionsJouables(): PositionsJouables
        + getPositionsEquipement(): PositionsEquipement
        + getPositionsObstacle(): PositionsObstacle
        + positionInDonjon(position: Position): boolean
        + estPrise(position: Position): boolean
        + {static} creerDonjonRichesse(Personnage[*]: listePersonnages):Donjon
        + {static} creerLabyrinthe(Personnage[*]: listePersonnages):Donjon
        + {static} creerDonjonDesGobelins(Personnage[*]: listePersonnages):Donjon
        + getPositionFromJouable(jouable: Jouable): Position
        + getJouableFromPosition(position: Position): Jouable
        + getEquipementFromPosition(position: Position): Equipement
        + {static} getDistance(p1: Position, p2: Position): double
        + ajoutObstacleMj(pos: Position): ActionResult
        + toString(): String
    }
    interface AffichageDonjonInterface <<interface>>
    {
        + {abstract} demanderLargeur() : int
        + {abstract} demanderLongeur() : int
        + {abstract} demanderPositionObstacle(donjon: Donjon, PO: PositionsObstacle) : Position
        + {abstract} PlacerObstacles(donjon: Donjon) : PositionsObstacle
        + {abstract} demanderPositionEquipement(donjon: Donjon, PE: PositionsEquipement) : Position
        + {abstract} placerEquipement(donjon: Donjon) : PositionsEquipement
        + {abstract} PlacerPersonnages(perso: List<Personnage>, donjon: Donjon) : PositionsJouables
    }
    class Position
    {
        - m_x : int
        - m_y : int
        + <<create>> Position(x: int, y: int)
        + <<create>> Position()
        + <<create>> Position(other: Position)
        + getX() : int
        + getY() : int
        + setX(m_x: int)
        + setY(m_y: int
        + equals(other: Object) : boolean
        + hashCode() : int
        + toString() : String
        + getPositionFromCode(code: String) : Position {static}
    }

    class PositionsDesObstacles
    {
        + <<create>>PositionsObstacle()
        + ajouterObstacle(position: Position)
        + getPosition() :Position[*]
        + containsObstacle(position: Position)
        + toString() : String
    }

    class PositionsDesEquipements
    {
       + <<create>> PositionsEquipement()
       + ajouterEquipement(equipement: Equipement, position: Position) : void
       + getEquipementFromPosition(position: Position) : Equipement
       + retirerEquipement(position: Position) : void
       + containsEquipement(position: Position) : boolean
       + getCasesOccupees() : Set<Position>
       + toString() : String
    }

    class PositionsDesJouables
    {
        + <<create>>PositionsJouables()
        + ajouterJouable(jouable: Jouable, position: Position)
        + getPositionJouable(jouable: Jouable) : Position
        + attaqueDuMj(j: Jouable, de: De) : int
        + getJouableFromPosition(position: Position) : Jouable
        + deplacerJouable(jouable: Jouable, position: Position, donjon: Donjon) : ActionResult
        + deplacementMj(jouable: Jouable, futurPosition: Position, donjon: Donjon) : ActionResult
        + containsJouable(position: Position) : boolean
        + getPositions() : HashMap<Position, Jouable>
        + size() : int
        + getListeJouables() : List<Jouable>
        + toString() : String
    }
}
Donjon "1" *--> "1 \nm_positionsEquipement" PositionsDesEquipements : détient
Donjon "1" *--> "1 \nm_positionsJouable" PositionsDesJouables : détient
Donjon "1" *--> "1 \nm_positionsObstacle" PositionsDesObstacles : détient

PositionsDesEquipements "1..*" o--> "1..* \nm_positionEquipement.value" Equipement : détient
PositionsDesEquipements "1..*" o--> "1..* \nm_positionEquipement.key" Position : détient
PositionsDesJouables "1..*" o--> "1..* \nm_positionJouable.value" jouable.personnage.Jouable : détient
PositionsDesJouables "1..*" o--> "1..* \nm_positionJouable.key" Position : détient
PositionsDesObstacles "1..*" o--> "1..* \nm_positionObstacle[*]" Position : détient


package partie
{
    class De
    {
        - m_nbDes: final int
        - m_nbFaces: final int
        + <<create>> De(nbDes: int, nbFaces: int)
        + <<create>> De()
        + jeter(): int
        + toString(): String
        + equals(other: Object): boolean
    }
     class Partie
        {
            + {static} DebuterPartie()
            + {static} explorerDonjon(donj: Donjon, nbDonjon: int)
            + {static} partieperdue(p: Personnage)
            + {static} gagnee()
            + {static} afficherGenerique()
        }
     class Tour
         {
             - m_numeroDeTour : int
             - m_numeroDeDonjon : int
             - m_actionRestante : int

             + Tour(donj : Donjon, numTour : int, numDonjon : int)
             + commencerTour() : boolean
             + jouer(j : Jouable) : boolean
             + getPersonnageMort() : Personnage
             + tousLesMonstresMorts() : boolean
             + getNumTour() : int
             + getActionRestante() : int
             + {static} partieperdue(p : Personnage)
         }
     Tour "1" o-- "1" Donjon : m_donjon
     Tour "1" o--> "1..*" jouable.Jouable : m_listeJouable[*]
}
package affichage{
    class AffichageDonjon implements AffichageDonjonInterface
    {
        - m_scaner : Scanner
        + {static} afficherDonjon(donjon: Donjon)
        + commencerCreation(): int
        + demanderChoixDonjon(): int
        + demanderNomDonjon(): String
        + demanderLargeur(): int
        + demanderLongeur(): int
        + PlacerObstacles(donjon: Donjon): PositionsObstacle
        + demanderPositionObstacle(donjon: Donjon, PO: PositionsObstacle): Position
        + placerEquipement(donjon: Donjon): PositionsEquipement
        + demanderPositionEquipement(donjon: Donjon, PE: PositionsEquipement): Position
    }
    class affichagePersonnage implements AffichagePersonnageInterface
    {
        - m_scanner : Scanner
        + choisirClasse() : Classe
        + choisirRace(perso : Personnage) : Race
        + AffichageLancerDe(Ca : CaracteristiquesBase)
        + choisirNom() : String
        + afficherCaracteristique(perso : Personnage)
    }
    class AffichageMonstre
    {
        + {static} choisirCaracteristiques() : CaracteristiquesBase
        + {static} choisirEspece() : int
        + {static} choisirEspecePersonaliser() : String
        + {static} choisirRepresentation() : String
        + {static} choisirDegatAttaque() : De
        + {static} choisirPorterAttaque() : int
        + {static} choisirArmure() : int
        + {static} afficherCaracteristique(monstr : Monstre)
        + {static} demanderEntier(scanner : Scanner, nomChamp : String) : int
    }
    class AffichageInitPartie
    {
        + {static} demanderNbJoueur() : int
        + {static} affichageEntreeDonjon(nomDonjon : String, numDonjon : int)
    }
    class AffichageTour {
          + {static} afficherTourMonstre(donj: Donjon, numDonjon: int, t: Tour, m: Monstre, lj: List<Jouable>): boolean
          + {static} afficherTourPersonage(donj: Donjon, numDonjon: int, t: Tour, p: Personnage, lj: List<Jouable>): boolean
          + {static} afficherEnteteDonjon(numDonjon: int, numTour: int, j: Jouable)
          + {static} afficherLesJouable(listeJouables: List<Jouable>, j: Jouable)
          + {static} afficherRecapPersonnage(p: Personnage)
          + {static} afficherRecapMonstre(m: Monstre)
          + {static} afficherActionsPersonnage(p: Personnage, donj: Donjon, actionRestante: int): boolean
          + {static} boolean afficherActionsMonstre(Monstre m, Donjon donj, int actionRestante)
          + {static} afficherSorts(Personnage p, Donjon donj)
          + {static} affichageBoogieWoogie(Donjon donj)
          + {static} affichageArmeMagique(donj : Donjon)
          + {static} affichageGuerison(donj : Donjon)
          + {static} choixActionMj() : int
          + {static} choixCaseDeplacementMj(donj : Donjon)
          + {static} choixAttaqueDuMj(donj : Donjon)
          + {static} ajouterObstacleMj(donj : Donjon)
          + {static} afficherDe(somme : int)
          + {static} afficherPerdue(p : Personnage)
          + {static} afficherGagnee()
    }

}

class main
{
    + {static} main(args: String[])
}

objet.arme.Arme "1" *--> "1 \nm_deDegats" partie.De : utilise
InitialiseurPartie .> Donjon : <<instantiate>>

Classe "0..*" o--> "0..* \nm_listeSorts" jouable.personnage.sorts.Sorts : a des

@enduml


