@startuml

'https://plantuml.com/sequence-diagram
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
skinparam linetype ortho
hide empty members

package jouable
{



    package personnage
    {
         abstract class Jouable <<abstract>>
            {
                + <<create>> Jouable()
                + {abstract} attaquer(other: Jouable)
                + {abstract} toString(): String
                + {abstract} getRepresentation(): String
                + getCurrentPv(): Integer
                + getPvMax(): Integer
                + getDexterite(): Integer
                + getVitesse(): Integer
                + getInit(): Integer
                + getForce(): Integer
            }
        class Personnage extends jouable.Jouable
        {
            - m_nom: String
            - m_listeSorts: Sorts[*]
            + <<create>> Personnage (nom: String, race: Race, classe: Classe, stats: CaracteristiquesBase)
            + equiperArme(Armure: armure)
            + equiperArmure(Arme: arme)
            + ramasser()
            + getNom(): String
            + toString(): String
            + getRepresentation(): String
        }
        interface AffichagePersonnageInterface <<interface>>
        {
            + choisirClasse() : String
            + choisirRace() : String
            + choisirNom() : String
            + afficherCaracteristiaque(CurrentPv: Integer, PvMax: Integer, Dexteriter: Integer, Force: Integer, Vitesse: Integer, Initiative: Integer) : String
        }


        Personnage "1" *--> "1 \nm_race" race.Race : est
        Personnage "1" *--> "1 \nm_classe" classe.Classe : possède

        package race
        {
            interface Race <<interface>>
            {
                + toString(): String
            }

            class Humain implements Race
            {
                + <<create>> Humain(stats: Caracteristiques)
                + <<create>> Humain()
                + getPv(): Integer
                + getCurrentPv(): Integer
                + getDexterite(): Integer
                + getVitesse(): Integer
                + getInit(): Integer
                + getForce(): Integer
                + toString(): String
            }

            class Nain implements Race
            {
                - m_force: Integer
                + <<create>> Nain(stats: Caracteristiques)
                + <<create>> Nain()
                + getForce(): Integer
                + toString(): String
            }

            class Elfe implements Race
            {
                - m_dexterite: Integer
                + <<create>> Elfe(stats: Caracteristiques)
                + <<create>> Elfe()
                + getDexterite(): Integer
                + toString(): String
            }

            class Halfelin implements Race
            {
                - m_dexterite: Integer
                - m_vitesse: Integer
                + <<create>> Halfelin(stats: Caracteristiques)
                + <<create>> Halfelin()
                + getDexterite(): Integer
                + getVitesse(): Integer
                + toString(): String
            }
        }

        package sorts
        {
            interface Sorts <<interface>>
            {
                + toString()
                + utiliser(lanceur: Personnage, Cibles: Jouable[*])
            }

            class Guerison implements Sorts
            {
                + toString()
                + utiliser(lanceur: Personnage, Object... cibles)
            }

            class BoogieWoogie implements Sorts
            {
                + toString()
                + utiliser(lanceur: Personnage, Object... cibles)
            }

            class ArmeMagique implements Sorts
            {
                + toString()
                + utiliser(lanceur: Personnage, Object... cibles)
            }

        }


        package classe
        {
            abstract class Classe <<abstract>>
            {
                - m_pv: Integer
                + toString(): String
                + <<create>> Classe(pv: Integer)
                + getPv(): Integer
                + getSorts(): Sorts[*]
            }

            class Guerrier extends Classe
            {
                + <<create>> Guerrier()
                + toString(): String
            }

            class Clerc extends Classe
            {
                + <<create>> Clerc()
                + toString(): String
            }

            class Magicien extends Classe
            {
                + <<create>> Magicien()
                + toString(): String
            }

            class Roublard extends Classe
            {
                + <<create>> Roublard()
                + toString(): String
            }
        }
    }

    package monstre
    {
        class Monstre extends jouable.Jouable
        {
            - m_numero: Integer
            - m_portee: Integer
            - m_degats: Integer
            - m_classeArmure: Integer
            - m_race: String
            + <<create>> Monstre(portee: Integer, degats: Integer, espece: String)
            + <<create>> Monstre(portee: Integer, degats: Integer, espece: String, numero: Integer)
            + getClasseArmure(): Integer
            + getRepresentation(): String
            + toString(): String
        }
        interface AffichageMonstreInterface <<interface>>
        {
            + choisirEspece() : String
            + choisirRepresentation() : String
            + choisirDegatAttaque() : String
            + choisirPorterAttaquechoisirPorterAttaque() : String
            + afficherCaracteristiaque(CurrentPv: Integer, PvMax: Integer, Dexteriter: Integer, Force: Integer, Vitesse: Integer, Initiative: Integer, Integer ClassArmure) : String
        }

    }
}

package stats
{
    class CaracteristiquesBase
    {
        - m_currentPv: Integer
        - m_pvMax: Integer
        - m_force: Integer
        - m_dexterite: Integer
        - m_vitesse: Integer
        - m_initiative: Integer
        - m_armure: Integer
        + <<create>> CaracteristiquesBase(pv: Integer, force: Integer, dexterite: Integer, vitesse: Integer, initiative: Integer , armure: Integer)
        + <<create>> CaracteristiquesBase(CA: CaracteristiquesBase)
        + <<create>> CaracteristiquesBase()
        + ajouterClasseBonus(Integer: pv)
        + getPvMax(): Integer
        + getCurrentPv(): Integer
        + getDexterite(): Integer
        + getVitesse(): Integer
        + getInit(): Integer
        + getForce(): Integer
        + getArmure(): Integer
        + toString(): String
        + setPv()
        + setDexterite()
        + setVitesse()
        + setInit(
        + setForce()
        + setArmure()
        + equals(other: CaracteristiquesBase): Boolean
        + toString(): String
    }

    Jouable "1" *--> "1 \nm_caracteristiques" stats.CaracteristiquesBase : détient
    Humain "1" *--> "1 \nm_caracteristiques" stats.CaracteristiquesBase : détient
}

package objet
{
    abstract class Equipement <<abstract>>
    {
        + getSymbole(): String
        + {abstract} equiper(perso: Personnage)
        + {abstract} ajouterBonus(bonus: Integer)
        + {abstract} getNomEquipement(): String
        + {abstract} equals(): Boolean
    }

    Equipement .> Personnage : <<use>>

    package armure
    {
        abstract class Armure <<abstract>> implements objet.Equipement
        {
            # m_classeArmure: Integer
            + <<create>> Armure(classeArmure: Integer)
            + <<create>> Armure()
            + equiper(perso: Personnage)
            + equiper(perso: Personnage)
            + getClasseArmure(): Integer
            + toString(): String
            + equals(other: Object): Boolean
        }

        abstract class ArmureLourde <<abstract>> extends Armure
        {
            - m_vitesse: Integer
            + <<create>> ArmureLourde(classeArmure: Integer)
            + <<create>> ArmureLourde()
            + equiper(perso: Personnage)
            + toString(): String
            + getVitesse(): Integer
            + equals(other: Object): Boolean
        }

        abstract class ArmureLegere <<abstract>> extends Armure
        {
            + <<create>> ArmureLegere()
            + <<create>> ArmureLegere(armure: Integer)
            + toString(): String
            + equals(other: Object): Boolean
        }

        class ArmureEcailles extends ArmureLegere
        {
            + <<create>> ArmureEcailles()
            + toString(): String
            + getNomEquipement(): String
            + equals(other: Object): Boolean
        }

        class DemiPlate extends ArmureLegere
        {
            + <<create>> DemiPlate()
            + getNomEquipement(): String
            + toString(): String
            + equals(other: Object): Boolean
        }

        class CoteMailles extends ArmureLourde
        {
            + <<create>> CoteMailles()
            + getNomEquipement(): String
            + toString(): String
            + equals(other: Object): Boolean
        }

        class Harnois extends ArmureLourde
        {
            + <<create>> Harnois()
            + getNomEquipement(): String
            + toString(): String
            + equals(other: Object): Boolean
        }
    }

    package arme
    {

        abstract class Arme <<abstract>> implements objet.Equipement
        {
            # m_degats: De
            # m_portee: Integer
            # m_bonusAttaque: Integer
            + <<create>> Arme(degats: Integer, portee: Integer)
            + <<create>> Arme()
            + ajouterBonus(bonus: Integer)
            + getDeDegats(): De
            + getPortee(): Integer
            + getBonusAttaque(): Integer
            + setDeDegats(degats: De)
            + setPortee(portee: Integer)
            + setBonusAttaque(bonus: Integer)
            + toString(): String
            + equals(other: Object): Boolean
        }


        package armedeguerre
        {

            abstract class ArmeDeGuerre <<abstract>> extends objet.arme.Arme
            {
                # m_vitesse: Integer
                # m_force: Integer
                + <<create>> ArmeDeGuerre(degats: De, portee: Integer, vitesse: Integer, force: Integer)
                + <<create>> ArmeDeGuerre()
                + equiper(perso: Personnage)
                + toString(): String
                + getVitesse(): Integer
                + setVitesse(vitesse: Integer)
                + getForce(): Integer
                + setForce(force: Integer)
                + equals(other: Object): Boolean
            }

            class EpeeLongue extends ArmeDeGuerre
            {
                + <<create>> EpeeLongue()
                + toString(): String
                + getNomEquipement(): String
                + equals(other: Object): Boolean
            }

            class Rapiere extends ArmeDeGuerre
            {
                + <<create>> Rapiere()
                + toString(): String
                + getNomEquipement(): String
                + equals(other: Object): Boolean
            }

            class EpeeDeuxMains extends ArmeDeGuerre
            {
                + <<create>> EpeeDeuxMains()
                + toString(): String
                + getNomEquipement(): String
                + equals(other: Object): Boolean
            }

        }

        package armedistance
        {

            abstract class ArmeDistance <<abstract>> extends objet.arme.Arme
            {
                + <<create>> ArmeDistance()
                + <<create>> ArmeDistance(degats: De, portee: Integer)
                + equiper(perso: Personnage)
                + toString(): String
            }

            class ArbaleteLegere extends ArmeDistance
            {
                + <<create>> ArbaleteLegere()
                + toString(): String
                + equals(other: Object): Boolean
                + getNomEquipement(): String
            }

            class Fronde extends ArmeDistance
            {
                + <<create>> Fronde()
                + toString(): String
                + getNomEquipement(): String
                + equals(other: Object): Boolean
            }

        }

        package armecourante
        {

            abstract class ArmeCourante <<abstract>> extends objet.arme.Arme
            {
                + <<create>> ArmeCourante()
                + <<create>> ArmeCourante(degats: De, portee: Integer)
                + toString(): String
                + equiper(perso: Personnage)
                + equals(other: Object): Boolean
            }

            class Baton extends ArmeCourante
            {
                + <<create>> Baton()
                + getNomEquipement(): String
                + toString(): String
                + equals(other: Object): Boolean
            }

            class MasseDarme extends ArmeCourante
            {
                + <<create>> MasseDarme()
                 + getNomEquipement(): String
                + toString(): String
                + equals(other: Object): Boolean
            }

            class ArcCourt extends ArmeDistance
            {
                + <<create>> ArcCourt()
                + equals(other: Object): Boolean
                + toString(): String
                + getNomEquipement(): String
            }

        }









    }
}

Personnage "1..*" *--> "1..* \nm_inventaire" objet.Equipement : possède
Personnage "1" *--> "0..1 \nm_arme" objet.arme.Arme : possède
Personnage "1" *--> "1 \nm_armure" objet.armure.Armure : possède

Classe "1..*" *--> "1..* \nm_listeEquipement" objet.Equipement : détient

package donjon
{

    class Donjon
    {
        - m_longueur: Integer
        - m_largeur: Integer
        + <<create>> Donjon(longueur: Integer, largeur: Integer)
        + verifCasePrise(Position): Boolean
        + getLargeur(): Integer
        + getLongueur(): Integer
        + afficher(): String
        + toString(): String
    }

    class Position
    {
        - m_x: Integer
        - m_y: Integer
        + <<create>> Position(x: Integer, y: Integer)
        + toString(): String
    }

    class PositionsDesObstacles
    {
       + <<create>> PositionsDesObstacles()
       + ajouterObstacle()
       + toString(): String
       + {static} deplacerObstacle(Position)
    }

    class PositionsDesEquipements
    {
       + <<create>> PositionsDesEquipements()
       + ajouterEquipement(Position, Equipement)
       + toString(): String
       + {static} deplacerEquipement(Position)
    }

    class PositionsDesJouables
    {
        + <<create>> PositionsDesJouables()
        + ajouterJouable(Position, Jouable)
        + toString(): String
        + {static} deplacerJouable(Position)
    }

}
Donjon "1" *--> "1 \nm_dicoItems" PositionsDesEquipements : détient
Donjon "1" *--> "1 \nm_dicoJouable" PositionsDesJouables : détient
Donjon "1" *--> "1 \nm_dicoObstacle" PositionsDesObstacles : détient

PositionsDesEquipements "1..*" o--> "1..* \nm_positionEquipement" Equipement : détient
PositionsDesJouables "1..*" o--> "1..* \nm_positionJouable" Jouable : détient
PositionsDesObstacles "1..*" o--> "1..* \nm_positionObstacle" Position : détient


package partie
{
    class De
    {
        - m_nbDes: final int
        - m_nbFaces: final int
        + <<create>> De(nbDes: int, nbFaces: int)
        + <<create>> De()
        + jeter(): int
        + toString(): String
        + equals(other: Object): boolean
    }
     class Partie
        {
            + {static} DebuterPartie()
            + {static} explorerDonjon(donj: Donjon, nbDonjon: int)
            + {static} partieperdue(p: Personnage)
            + {static} gagnee()
            + {static} afficherGenerique()
        }
     class Tour
         {
             - m_numeroDeTour : int
             - m_numeroDeDonjon : int
             - m_actionRestante : int

             + Tour(donj : Donjon, numTour : int, numDonjon : int)
             + commencerTour() : boolean
             + jouer(j : Jouable) : boolean
             + getPersonnageMort() : Personnage
             + tousLesMonstresMorts() : boolean
             + getNumTour() : int
             + getActionRestante() : int
             + {static} partieperdue(p : Personnage)
         }
     Tour "1" o-- "1" Donjon : m_donjon
     Tour "1" o--> "1..*" jouable.Jouable : m_listeJouable[*]
}
package affichage{
    class AffichageDonjon implements AffichageDonjonInterface
    {
        - m_scaner : Scanner
        + {static} afficherDonjon(donjon: Donjon)
        + commencerCreation(): int
        + demanderChoixDonjon(): int
        + demanderNomDonjon(): String
        + demanderLargeur(): int
        + demanderLongeur(): int
        + PlacerObstacles(donjon: Donjon): PositionsObstacle
        + demanderPositionObstacle(donjon: Donjon, PO: PositionsObstacle): Position
        + placerEquipement(donjon: Donjon): PositionsEquipement
        + demanderPositionEquipement(donjon: Donjon, PE: PositionsEquipement): Position
    }
    class affichagePersonnage implements AffichagePersonnageInterface
    {
        - m_scanner : Scanner
        + choisirClasse() : Classe
        + choisirRace(perso : Personnage) : Race
        + AffichageLancerDe(Ca : CaracteristiquesBase)
        + choisirNom() : String
        + afficherCaracteristique(perso : Personnage)
    }
    class AffichageMonstre
    {
        + {static} choisirCaracteristiques() : CaracteristiquesBase
        + {static} choisirEspece() : int
        + {static} choisirEspecePersonaliser() : String
        + {static} choisirRepresentation() : String
        + {static} choisirDegatAttaque() : De
        + {static} choisirPorterAttaque() : int
        + {static} choisirArmure() : int
        + {static} afficherCaracteristique(monstr : Monstre)
        + {static} demanderEntier(scanner : Scanner, nomChamp : String) : int
    }
    class AffichageInitPartie
    {
        + {static} demanderNbJoueur() : int
        + {static} affichageEntreeDonjon(nomDonjon : String, numDonjon : int)
    }
    class AffichageTour {
          + {static} afficherTourMonstre(donj: Donjon, numDonjon: int, t: Tour, m: Monstre, lj: List<Jouable>): boolean
          + {static} afficherTourPersonage(donj: Donjon, numDonjon: int, t: Tour, p: Personnage, lj: List<Jouable>): boolean
          + {static} afficherEnteteDonjon(numDonjon: int, numTour: int, j: Jouable)
          + {static} afficherLesJouable(listeJouables: List<Jouable>, j: Jouable)
          + {static} afficherRecapPersonnage(p: Personnage)
          + {static} afficherRecapMonstre(m: Monstre)
          + {static} afficherActionsPersonnage(p: Personnage, donj: Donjon, actionRestante: int): boolean
          + {static} boolean afficherActionsMonstre(Monstre m, Donjon donj, int actionRestante)
          + {static} afficherSorts(Personnage p, Donjon donj)
          + {static} affichageBoogieWoogie(Donjon donj)
          + {static} affichageArmeMagique(donj : Donjon)
          + {static} affichageGuerison(donj : Donjon)
          + {static} choixActionMj() : int
          + {static} choixCaseDeplacementMj(donj : Donjon)
          + {static} choixAttaqueDuMj(donj : Donjon)
          + {static} ajouterObstacleMj(donj : Donjon)
          + {static} afficherDe(somme : int)
          + {static} afficherPerdue(p : Personnage)
          + {static} afficherGagnee()
    }

}

class main
{
    + {static} main(args: String[])
}

objet.arme.Arme "1" *--> "1 \nm_deDegats" partie.De : utilise
InitialiseurPartie .> Donjon : <<instantiate>>

Classe "0..*" o--> "0..* \nm_listeSorts" jouable.personnage.sorts.Sorts : a des

main .> MaitreDuJeu : <<instantiate>>
main .> Donjon : <<instantiate>>
main .> De : <<instantiate>>

MaitreDuJeu "1" o--> "1 \nm_donjon" Donjon : gère

@enduml


